name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  cancel-previous:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  format:
    runs-on: ubuntu-latest
    needs: cancel-previous

    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        components: rustfmt
    - name: Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  lint:
    runs-on: ubuntu-latest
    needs: cancel-previous

    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
      with:
        components: clippy
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

  test:
    runs-on: ubuntu-latest
    needs: cancel-previous

    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Install Toolchain
      uses: actions-rs/toolchain@v1
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
